name: cli-action

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ proj-go ]

jobs:
  codacy-analysis-cli:
    name: start
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set-up go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Run Staticcheck and Gosec
        uses: codacy/codacy-analysis-cli-action@master
        with:
          run-staticcheck: "true"
          run-gosec: "true"
          upload: true
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          run-docker-tools: "false"
      - name: Run Staticcheck and Gosec
        uses: codacy/codacy-analysis-cli-action@master
        with:
          run-staticcheck: "true"
          run-gosec: "true"
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          run-docker-tools: "false"
      - name: Run Staticcheck and Gosec
        uses: codacy/codacy-analysis-cli-action@master
        with:
          run-staticcheck: "true"
          run-gosec: "true"
          upload: true
          run-docker-tools: "false"
            - name: Run Staticcheck and Gosec
        uses: codacy/codacy-analysis-cli-action@master
        with:
          run-staticcheck: "true"
          run-gosec: "true"
          upload: true
          api-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          run-docker-tools: "false"
      # - name: Run Deadcode
      #   run: |
      #       export CODACY_CODE=$GITHUB_WORKSPACE
      #       go build
      #       echo "$CODACY_CODE"
      #       docker run \
      #             --rm=true \
      #             --env CODACY_CODE="$CODACY_CODE" \
      #             --volume /var/run/docker.sock:/var/run/docker.sock \
      #             --volume "$CODACY_CODE":"$CODACY_CODE" \
      #             --volume /tmp:/tmp \
      #             codacy/codacy-analysis-cli \
      #               analyze --tool deadcode \
      #             --allow-network \
      #             --upload \
      #             --verbose \
      #             --project-token ${{ secrets.CODACY_PROJECT_TOKEN }}
      # - name: Run Aligncheck
      #   run: |
      #       export CODACY_CODE=$GITHUB_WORKSPACE
      #       go build
      #       docker run \
      #             --rm=true \
      #             --env CODACY_CODE="$CODACY_CODE" \
      #             --volume /var/run/docker.sock:/var/run/docker.sock \
      #             --volume "$CODACY_CODE":"$CODACY_CODE" \
      #             codacy/codacy-analysis-cli \
      #               analyze --tool aligncheck \
      #             --allow-network \
      #             --upload \
      #             --verbose \
      #             --project-token ${{ secrets.CODACY_PROJECT_TOKEN }}
