name: Go

on:
  push:
    branches: [ proj-go ]
  pull_request:
    branches: [ proj-go ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
    - uses: actions/checkout@v3
    - run: "go vet ./..."
    - uses: dominikh/staticcheck-action@v1.2.0
      with:
        version: "2022.1"
        install-go: false
        cache-key: ${{ matrix.go }}
        working-directory: ${{ matrix.dir }}
    - name: send results to codacy
      run: | 
           /home/runner/work/_temp/staticcheck -f json ./...  | \ 
            java -jar codacy-staticcheck-3.0.5.jar  | \  
            curl -XPOST -L -H "project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}" \
                -H "Content-type: application/json" -d @- \
                "https://api.codacy.com/2.0/commit/$GITHUB_SHA/issuesRemoteResults"
            curl -XPOST -L -H "project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}" \
                -H "Content-type: application/json" \
                "https://api.codacy.com/2.0/commit/$GITHUB_SHA/resultsFinal"
