name: StaticCheck

on: ["proj-go"]

jobs:
  codacy-analysis-cli:
    name: start
    runs-on: ubuntu-latest
    steps:
      - name: run StaticCheck
        uses: codacy/codacy-analysis-cli-action@master
        with:
          tool: staticcheck
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          upload: true
          max-allowed-issues: 2147483647
          run-staticcheck: "true"